---
- name: Homeserver Deployment
  hosts: all
  become: true
  gather_facts: true
  any_errors_fatal: true
  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: roles/home.apps