name: molecule lint

on:
    push:
      branches-ignore:
        - 'main'

jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          path: "${{ github.repository }}"
      - name: Molecule for Ansible - lint
        uses: MonolithProjects/action-molecule@v1.4.3
        with:
          molecule_command: lint