name: molecule lint

on:
    push:
      branches-ignore:
        - 'main'

jobs:
  lint:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
    steps:
      - name: checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          path: "${{ github.repository }}"
      - name: Molecule for Ansible - lint
        uses: MonolithProjects/action-molecule@v1.4.3
        with:
          molecule_command: lint